package com.spendstreak.app

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.spendstreak.app.data.SpendStreakDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

// Runs SpendStreakDatabase's hand-written migrations against the actual exported schema
// for each version (see app/schemas, generated by ksp's room.schemaLocation arg), so a
// migration that would corrupt or fail to open a real user's upgrade is caught here rather
// than in production. Only migrations added after schema export was enabled can be covered
// this way — see BudgetMathTest's sibling commentary in SpendStreakViewModel for why the
// 5 migrations shipped before this (3->4 through 7->8) aren't retroactively testable here.
@RunWith(AndroidJUnit4::class)
class MigrationTest {
    private val dbName = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        SpendStreakDatabase::class.java
    )

    @Test
    fun migrate8To9_addsCategoryBudgetsTableAndRoundTripsARow() {
        helper.createDatabase(dbName, 8).close()

        val db = helper.runMigrationsAndValidate(dbName, 9, true, SpendStreakDatabase.MIGRATION_8_9)

        db.execSQL("INSERT INTO category_budgets (categoryId, monthlyLimit) VALUES (1, 250.5)")
        val cursor = db.query("SELECT categoryId, monthlyLimit FROM category_budgets")
        assertTrue(cursor.moveToFirst())
        assertEquals(1, cursor.getInt(cursor.getColumnIndexOrThrow("categoryId")))
        assertEquals(250.5, cursor.getDouble(cursor.getColumnIndexOrThrow("monthlyLimit")), 0.0001)
        cursor.close()
        db.close()
    }
}
